#!/usr/bin/env python

"""
Usage: sdssDR9findingChart.py fileWithAstroObjects

fileWithAstroObjects is a text file with an astronomical source name
per line. Non-valid names are ignored. The result is a finding chart
from SDSS DR9 as a JPEG downloaded in the directory from which the
sdssDR9findingChart.py script is called.

See details of the DS9 Finding chart web service at:
  http://skyserver.sdss3.org/dr9/en/tools/chart/chart.asp
"""

from __future__ import division

import functools
import multiprocessing
import os
import sys
import time
import urllib

sesameQueryUrl = 'http://cdsws.u-strasbg.fr/axis/services/Sesame?'  +\
                 'method=sesame&resultType=p&all=true&service=NSVA' +\
                 '&name=%(name)s'
sdssQueryUrl   = 'http://skyservice.pha.jhu.edu/DR9/ImgCutout/getjpeg.aspx?'

def download_chart(args):
    """ Download the finding chart for an astronomical object (first element of
    the two-element tuple 'args') to a path (second element of the tuple)"""

    object_name, img_path = args

    # Perform the Sesame query
    try:
        sesameQuery = sesameQueryUrl % {'name': urllib.quote(object_name.strip())}
        print "Processing Sesame query for %s" % object_name

        sesameResponse = urllib.urlopen(sesameQuery).readlines()
        ra, dec = filter(lambda x: x.find('%J') == 0, sesameResponse)[0].split(' ')[1:3]

        # SDSS DR9
        sdssParamsDict = {
            'ra':     ra,
            'dec':    dec,
            'scale':  0.396127,
            'width':  1024,
            'height': 1024,
            'opt':   'G',
            'query': 'SR(10,10)'
        }

        try:
            print "Querying SDSS for coordinates %s %s (%s)" % (ra, dec, object_name)
            url = sdssQueryUrl + urllib.urlencode(sdssParamsDict)

            def remove(path):
                """ Remove a partially downloaded file, ignore errors """
                try: os.unlink(path)
                except: pass

            try:
                urllib.urlretrieve(url, filename = img_path)
                print "Download of %s completed" % img_path
            except KeyboardInterrupt:
                remove(img_path)
                sys.exit(1)
            except:
                remove(img_path)
                print "Download of %s failed" % img_path

        except Exception, e:
            print "Error. Coordinates %s %s not found in SDSS" % (ra, dec)

    except Exception, e:
        print "Error. Coordinates for %s not found in Sesame" % object_name
        print e


with open(sys.argv[1],'r') as f:
    # Get only non-empty lines, stripped of trailing blanks and \n
    objects = filter(lambda x: len(x)>0, map(lambda x: x.strip(), f.readlines()))

    # Use a pool of workers and download the images in parallel.
    # The number of workers is that of CPUs in the system.
    pool = multiprocessing.Pool(multiprocessing.cpu_count())
    map_async_args = ((name, name.strip() + '.jpg') for name in objects)
    result = pool.map_async(download_chart, map_async_args)

    while not result.ready():
        time.sleep(1)
    result.get()      # reraise exceptions of the remote call, if any

